### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by ammarm08** [jabyess/mailroad#103]
We need tests so that we can go forth and prosper

**Comment by jabyess** [comment]
Also look into https://facebook.github.io/jest/ because its built for react.

**Comment by ammarm08** [comment]
server side suite at PR #107

**Comment by ammarm08** [comment]
need to create a test db, create expected tables in it, and seed it with docs before running all tests, then wipe that db after the tests are done

will have to make sure that running tests dont actually meddle with actual user data haha

**Comment by ammarm08** [comment]
update (6/13): have a client-tests branch that I'm adding some basic tests in for using Jest. once those are up and merged, i'll close this issue

**Comment by jabyess** [comment]
Fixed by #125, closing
