### ISSUE TITLE
flow js config/support

### ISSUE THREAD

**Issue by jabyess** [jabyess/mailroad#105]
Get this shiot started.

**Comment by ammarm08** [comment]
For reference:

https://flow.org/en/docs/getting-started/
https://flow.org/en/docs/frameworks/react/
https://www.robinwieruch.de/the-soundcloud-client-in-react-redux-flow/
http://mherman.org/blog/2016/12/23/building-a-restful-api-with-node-and-flow/#.WSiPLSErLCI

**Comment by jabyess** [comment]
This is not really all that easy to set up or use. Closing for now.
