### ISSUE TITLE
consider sending pouchdb requests to express backend, not directly to couchdb

### ISSUE THREAD

**Issue by ammarm08** [jabyess/mailroad#112]
This will be especially important when the app and the database live on different machines -- the client should only really be able to get stuff by asking the express server for it.

this would help in several ways:

- **Validation**: you don't want users maliciously/accidentally dropping entire tables from the DB.
- **Abstraction**: the server should be the proxy between the client and the things they want
- **Portability**: the location of a database shouldn't affect client code. they should just make requests and get things back

**Comment by jabyess** [comment]
Unfortunately I don't know of a way to have pouchdb talk to anything other than couchdb. the API doesn't provide any syntax for making manual requests, all you give it is a connection string/url and it does everything for you.

https://pouchdb.com/api.html#replication

I agree with your ideas in general though. There may be a better way to solve this.
